name: 'table-backend'

services:
  backend:
    image: table-backend:latest
    container_name: table-backend
    build:
      context: ./
      dockerfile: Dockerfile
      target: development
    restart: always
    tty: true
    stdin_open: true
    env_file: .env
    command: npm run start:dev
    ports:
      - '8002:8000'
    volumes:
      - .:/app
    networks:
      - table

  database:
    image: postgres:17-alpine
    container_name: table-database
    restart: always
    ports:
      - '${FORWARD_DB_PORT:-5433}:5432'
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres123}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_DB: ${DB_NAME:-table_ui}
    volumes:
      - PG_DATA:/var/lib/postgresql/data
    networks:
      - table

  pgAdmin:
    image: dpage/pgadmin4
    container_name: table-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@gmail.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
      - PG_ADMIN:/var/lib/pgadmin
    restart: always
    ports:
      - '${PGADMIN_FORWARD_PORT:-8080}:80'
    networks:
      - table

volumes:
  PG_ADMIN: {}
  PG_DATA: {}

networks:
  table:
    name: table-network
    external: true
