name: "table-frontend"

services:
  frontend:
    image: table-frontend:latest
    container_name: table-frontend
    build:
      context: ./
      dockerfile: Dockerfile
      target: production
    restart: always
    tty: true
    stdin_open: true
    env_file: .env
    ports:
      - "8001:8001"
    volumes:
      - .:/app
